<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

## 1. Exercise 1 (Total recall?)

1. Two similarities between lists and arrays.
- First, they both use zero-index counting, meaning that I need to count starting from 0 when identifying an element in the list/array by its address. Secondly, the order matters.

2. Two differences between lists and arrays.
- First, arrays only accept text when storing data. Second, certain arithmetic operations on lists applies to the list as a whole, while an operation on an array applies on each element individually.

3. What is a dictionary?
- Where each element is linked to a key that can be used to access the element in the dictionary.

## 2. Exercise 2 (Indexing)

In [2]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])
print(py_list[2])
print(py_list[4])
print(py_list[6])
print(py_list[8])


a1
c3
e5
g7
i9


## 3. Exercise 3 (Index Again)

In [3]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']

In [8]:
print(elements[3])
print(elements[-4])

Beryllium
Nitrogen


## 4. Exercise 4 (How many ones)

In [9]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

In [12]:
import numpy as np

In [13]:
np_array = np.array(numbers)

In [22]:
sum(np_array == 1)

np.int64(9)

## 5. Exercise 5 (Statistics)

In [23]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [25]:
x1_array = np.array(x_1)
x2_array = np.array(x_2)

In [30]:
np.mean(x1_array)

np.float64(38.5)

In [31]:
np.mean(x2_array)

np.float64(302.5)

In [32]:
np.std(x1_array)

np.float64(32.41990129534635)

In [33]:
np.std(x2_array)

np.float64(326.0893282522444)

In [36]:
x1_array[0]-np.mean(x1_array)

np.float64(-37.5)

In [37]:
x1_array - np.mean(x1_array)

array([-37.5, -34.5, -29.5, -22.5, -13.5,  -2.5,  10.5,  25.5,  42.5,
        61.5])

In [38]:
(x1_array - np.mean(x1_array))*(x2_array - np.mean(x2_array))

array([11306.25, 10160.25,  8127.25,  5366.25,  2396.25,   216.25,
         425.25,  5342.25, 18126.25, 42896.25])

In [ ]:
sum((x1_array - np.mean(x1_array)) * (x2_array - np.mean(x2_array)))

np.float64(104362.5)

In [54]:
sum((x1_array - np.mean(x1_array))**2) * sum((x2_array - np.mean(x2_array))**2)

np.float64(11176261346.25)

In [55]:
np.sqrt(sum((x1_array - np.mean(x1_array))**2) * sum((x2_array - np.mean(x2_array))**2))

np.float64(105717.8383540356)

In [ ]:
sum((x1_array - np.mean(x1_array)) * (x2_array - np.mean(x2_array))) / np.sqrt(sum((x1_array - np.mean(x1_array))**2) * sum((x2_array - np.mean(x2_array))**2)) # Pearson Correlation Coeff. Calculation

np.float64(0.9871796626270701)

In [ ]:
np.corrcoef(x1_array, x2_array) # calculating r using np.corrcoef

array([[1.        , 0.98717966],
       [0.98717966, 1.        ]])

Verified that both the manual formulation and np.corrcoef returned the same value of r. Yay